### PR TITLE
implementation of allocated, in-use metrics

### PR DESCRIPTION
**Pull request by msillence**
issue #148 feature request for more metrics
initial first stab

Project tests wouldn't run on the java 11 version I had without the pom upgrades

I've not worked out testing yet

### CODE REVIEW

**Comment by msillence** [comment]
So from what I can see `slots` in the `live` queue migrate into thread locals and then we have no global visibility of them

The connection may not be activly in use but has been used recently enough still to be cached in a local thread,  I should just add that to the docs

**Comment by chrisvest** [comment]
A slot that is claimed from a thread local (TLR_CLAIMED) will already be in the live queue. Hence this is a separate state, and also why releasing such claims do not return them to the live queue.

**Comment by msillence** [comment]
> A slot that is claimed from a thread local (TLR_CLAIMED) will already be in the live queue. Hence this is a separate state, and also why releasing such claims do not return them to the live queue.

I'm not sure that's what i'm seeing, my testing shows that the live queue populates to 10 items, I request items and the live queue diminishes but the `size` variable staus at 10, my iterator only sees around 8 and most of those are as expected in the TLR_CLAIMED state. I was expecting that the live queue would stay at 10 but looking at the code I think we pop some of the items off?

**Comment by linking12** [comment]
@chrisvest  is this PR ready for merge?

**Comment by chrisvest** [comment]
I don't yet have permission to work on this project.

**Comment by chrisvest** [comment]
Moving this to #163

**Pull request closed without merging**
